# Generated by Django 5.2.11 on 2026-02-23 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('jobtitle', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('status_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
